// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA45WIrdxQtTTyWFGuIUwkEOeV4xxkzWJs',
    appId: '1:217847087461:web:1c3a183b5d6418ce72a18c',
    messagingSenderId: '217847087461',
    projectId: 'crudoperation007',
    authDomain: 'crudoperation007.firebaseapp.com',
    storageBucket: 'crudoperation007.appspot.com',
    measurementId: 'G-NDK0GQM65Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwPTeJ9pnhoc0duErQwsVjbeN_hhWVWxE',
    appId: '1:217847087461:android:4e325ee69d061ce672a18c',
    messagingSenderId: '217847087461',
    projectId: 'crudoperation007',
    storageBucket: 'crudoperation007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACt8T0IzQSRZZZK1uN5wi68x4VLcPc3GM',
    appId: '1:217847087461:ios:59b6c3d75450bf8b72a18c',
    messagingSenderId: '217847087461',
    projectId: 'crudoperation007',
    storageBucket: 'crudoperation007.appspot.com',
    iosBundleId: 'com.example.providerdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACt8T0IzQSRZZZK1uN5wi68x4VLcPc3GM',
    appId: '1:217847087461:ios:06f35020d058fac172a18c',
    messagingSenderId: '217847087461',
    projectId: 'crudoperation007',
    storageBucket: 'crudoperation007.appspot.com',
    iosBundleId: 'com.example.providerdemo.RunnerTests',
  );
}
